from .util import DatetimeHelper

# Execution datetime
DATETIME_EXECUTION = DatetimeHelper.current_datetime_string()

# Folder paths
RESULTS_FILE_FOLDER = "results"
RESULTS_RAW_FILE_FOLDER = "raw"
RESULTS_PREPROCESSED_FILE_FOLDER = "preprocessed"
OUTPUT_FILE_PATH = f"{RESULTS_FILE_FOLDER}/{RESULTS_RAW_FILE_FOLDER}/{DATETIME_EXECUTION}_output.txt"
STATS_FILE_PATH = f"{RESULTS_FILE_FOLDER}/{RESULTS_RAW_FILE_FOLDER}/{DATETIME_EXECUTION}_stats.csv"
RESULTS_PREPROCESSED_FILE_PATH = f"{RESULTS_FILE_FOLDER}/{RESULTS_PREPROCESSED_FILE_FOLDER}/{DATETIME_EXECUTION}_stats.csv"

# Measure tag prefix
PREFIX_MEASURE_TAG = "measure_label-"
PREFIX_MEASURE_TAG_FILE_NAME = f"{PREFIX_MEASURE_TAG}filename"
